name: terraform plan
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "hello"
      - name: "say good bye"
        run: echo "good bye"
